// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF5c7oV5mJqNi0MFETz7W1acqGnYSv3y0',
    appId: '1:1057944027480:web:e677425bd02fb39698252d',
    messagingSenderId: '1057944027480',
    projectId: 'auto-picker-7ed1f',
    authDomain: 'auto-picker-7ed1f.firebaseapp.com',
    storageBucket: 'auto-picker-7ed1f.appspot.com',
    measurementId: 'G-XEZC3Q00J7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsORwv-lA-LR8gHCJ9oE9f8WZnhCykA-0',
    appId: '1:1057944027480:android:486fa790174bfb2a98252d',
    messagingSenderId: '1057944027480',
    projectId: 'auto-picker-7ed1f',
    storageBucket: 'auto-picker-7ed1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCV83LuJCD45afz9rJsK-6sKr_tHCnjeQ',
    appId: '1:1057944027480:ios:de600e16935e240798252d',
    messagingSenderId: '1057944027480',
    projectId: 'auto-picker-7ed1f',
    storageBucket: 'auto-picker-7ed1f.appspot.com',
    androidClientId: '1057944027480-pamog2mna0hhtcbustkim2ov9pjjchdq.apps.googleusercontent.com',
    iosClientId: '1057944027480-if7fk75g6b16cqsbksn9asgaahic0ska.apps.googleusercontent.com',
    iosBundleId: 'com.tstc',
  );
}
